# -*- coding: utf-8 -*-
"""coding loop 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y32oVUlwWIOFD1gYN_pgY-hSvyV8-gq6
"""

def print_positive_numbers(input_list):
  positive_numbers=[num for num in input_list if num>0]
  return positive_numbers

list1=[12,-7,5,64,-14]
list2=[12,14,-95,3]

output1=print_positive_numbers(list1)
output2=print_positive_numbers(list2)

print("Input:","list1=",list1,"Output:",output1)
print("Input:","list2=",list2,"Output:",output2)