# -*- coding: utf-8 -*-
"""creating loops!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xLMDFXiJ8734ANPc84oqh8sl7hokI9WI
"""

def fibonacci(limit):
  fib_sequence=[0,1]
  while fib_sequence[-1]+fib_sequence[-2]<=limit:
    fib_sequence.append(fib_sequence[-1]+fib_sequence[-2])
  return fib_sequence

limit=int(input("Enter the limit for Fibonacci numbers:"))
fib_numbers=fibonacci(limit)
print("Fibonacci number up to",limit,"are:",fib_numbers)